---
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  License: Apache-2.0
Description: >-
  CloudFront web distribution with S3 origin and IAM users.
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join: ['-',[Ref: 'AWS::StackName',Ref: 'AWS::AccountId']]
      AccessControl: PublicRead
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: Bucket
      PolicyDocument:
        Statement:
          - Action:
            - "s3:*"
            Effect: Allow 
            Resource:
              Fn::Sub: arn:aws:s3:::${Bucket}/*
            Principal: "*"
Outputs:
  BucketURL:
    Value:
      Fn::Join: ['',['s3://',Ref: 'AWS::StackName',Ref: 'AWS::AccountId']]
    Description: Name of S3 Bucket to hold application content
...
